//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference
    {
        public int conference_number { get; set; }
        public string Title { get; set; }
        public string Date { get; set; }
        public Nullable<int> venueid { get; set; }
        public int spakerid { get; set; }
    }
}
