//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UMWEBDBEntities1 : DbContext
    {
        public UMWEBDBEntities1()
            : base("name=UMWEBDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendeeregistration> attendeeregistrations { get; set; }
        public virtual DbSet<conference> conferences { get; set; }
        public virtual DbSet<paper> papers { get; set; }
        public virtual DbSet<speaker> speakers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<venue> venues { get; set; }
    }
}
