//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string publishdate { get; set; }
        public int conferenceid { get; set; }
    }
}
