//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue
    {
        public int venueID { get; set; }
        public string venuename { get; set; }
        public string venuetype { get; set; }
        public int venuecapacity { get; set; }
        public string country { get; set; }
    }
}
